"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function StrengthsWeaknessesPage(){
 const params=useParams<{id:string}>();const router=useRouter();const [data,setData]=useState<any|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return;}const base=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";const res=await fetch(base+"/matches/"+params.id+"/intelligence/matrix",{headers:{Authorization:"Bearer "+session.access_token}});const j=await res.json().catch(()=>null);const raw=j&&typeof j==="object"&&"data" in j?j.data:j;setData(raw&&typeof raw==="object"?raw:null);setLoading(false)})()},[params.id,router]);
 const list=(v:any)=>Array.isArray(v)?v:[];
 return <main className="fos-shell"><aside className="fos-sidebar"><div className="fos-brand"><strong>◆ 360<span>FOS</span></strong><small>Tactical Intelligence</small></div><nav><Link href="/">⌂ <span>Dashboard</span></Link><Link className="active" href="/matches">▣ <span>Matches</span></Link><Link href="/opponents">◌ <span>Opponents</span></Link><Link href="/training">⚽ <span>Training</span></Link><Link href="/reports">▤ <span>Reports</span></Link></nav></aside><section className="fos-main"><div className="breadcrumb-row"><Link href="/matches">Matches</Link><span>›</span><Link href={"/matches/"+params.id}>Workspace</Link><span>›</span><b>Strengths & Weaknesses</b></div><section className="page-heading"><div><div className="crumb">TACTICAL INTELLIGENCE / DIAGNOSIS</div><h1>Strengths & Weaknesses</h1><p>Separate our repeatable strengths and weaknesses from the opponent's tactical profile.</p></div><Link className="primary-action" href={"/matches/"+params.id+"/intelligence"}>Open Intelligence Matrix →</Link></section>{loading?<div className="empty-state">Loading...</div>:!data?<div className="empty-state">Unable to load tactical diagnosis.</div>:<section className="intelligence-summary"><article className="intel-summary-card positive"><span>Our Strengths</span><strong>{list(data.ourStrengths).length}</strong><small>Behaviours we can exploit</small></article><article className="intel-summary-card negative"><span>Our Weaknesses</span><strong>{list(data.ourWeaknesses).length}</strong><small>Behaviours to improve</small></article><article className="intel-summary-card negative"><span>Opponent Strengths</span><strong>{list(data.opponentStrengths).length}</strong><small>Threats to control</small></article><article className="intel-summary-card positive"><span>Opponent Weaknesses</span><strong>{list(data.opponentWeaknesses).length}</strong><small>Spaces to attack</small></article></section>}<div className="training-cards" style={{marginTop:24}}>{[["Our Strengths",data?.ourStrengths],["Our Weaknesses",data?.ourWeaknesses],["Opponent Strengths",data?.opponentStrengths],["Opponent Weaknesses",data?.opponentWeaknesses]].map(([title,values])=><article className="workspace-card training-card" key={title as string}><span className="section-kicker">{title as string}</span>{list(values).length===0?<p>No findings yet.</p>:list(values).map((x:any,i:number)=><div className="match-card-bottom" key={x.id??i}><strong>{x.behaviour}</strong><span>{x.phase??"General"} · score {x.score??0}</span></div>)}</article>)}</div></section></main>;
}
