"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function OpponentPage(){
 const params=useParams<{id:string}>(); const router=useRouter(); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return;}const base=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";const res=await fetch(base+"/matches/"+params.id+"/evidence",{headers:{Authorization:"Bearer "+session.access_token}});const j=await res.json().catch(()=>null);const raw=j&&typeof j==="object"&&"data" in j?j.data:j;setItems(Array.isArray(raw)?raw.filter((x:any)=>x.analysisType==="OPPONENT"):[]);setLoading(false)})()},[params.id,router]);
 return <main className="fos-shell"><aside className="fos-sidebar"><div className="fos-brand"><strong>◆ 360<span>FOS</span></strong><small>Tactical Intelligence</small></div><nav><Link href="/">⌂ <span>Dashboard</span></Link><Link className="active" href="/matches">▣ <span>Matches</span></Link><Link href="/opponents">◌ <span>Opponents</span></Link><Link href="/training">⚽ <span>Training</span></Link><Link href="/reports">▤ <span>Reports</span></Link></nav></aside><section className="fos-main"><div className="breadcrumb-row"><Link href="/matches">Matches</Link><span>›</span><Link href={"/matches/"+params.id}>Workspace</Link><span>›</span><b>Opponent</b></div><section className="page-heading"><div><div className="crumb">MATCH / OPPONENT</div><h1>Opponent Analysis</h1><p>Review opponent evidence, behaviours, strengths and weaknesses captured during the match analysis.</p></div><Link className="secondary-action" href={"/matches/"+params.id+"/evidence"}>Evidence Capture →</Link></section>{loading?<div className="empty-state">Loading...</div>:items.length===0?<div className="empty-state"><h2>No opponent evidence captured yet.</h2><p>Use Evidence Capture and select Opponent to build the scouting picture.</p><Link className="primary-action" href={"/matches/"+params.id+"/evidence"}>Scout Opponent</Link></div>:<section className="training-cards">{items.map((x:any)=><article className="workspace-card training-card" key={x.id}><span className="section-kicker">{x.phase?.replaceAll("_"," ")}</span><h2>{x.event}</h2><p>{x.note}</p><div className="training-grid"><Field label="Minute" value={String(x.minute)+"'"} /><Field label="Zone" value={x.zone}/><Field label="Impact" value={String(x.impact??3)+"/5"}/></div></article>)}</section>}</section></main>;
}
function Field({label,value}:{label:string;value?:string|null}){return <div className="training-field"><span>{label}</span><p>{value||"Not defined"}</p></div>}
