"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Report={session:any;runtime:any;assessment:any;behaviours:any[];actions:any[];summary:{successRate:number;targetRate:number;totalReps:number;transferRating:string;status:string}};
const baseUrl=()=>process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";

export default function SessionPerformanceReport(){
 const params=useParams<{id:string}>();const router=useRouter();
 const [report,setReport]=useState<Report|null>(null);const [loading,setLoading]=useState(true);const [generating,setGenerating]=useState(false);const [error,setError]=useState("");
 async function auth(){const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return null}return session}
 async function load(){const s=await auth();if(!s)return;const list=await fetch(baseUrl()+"/matches/"+params.id+"/training-sessions",{headers:{Authorization:"Bearer "+s.access_token}});const j=await list.json();const session=(j.data??[]).find((x:any)=>x.status==="COMPLETED")??(j.data??[])[0];if(!session){setError("No training session found.");setLoading(false);return}const r=await fetch(baseUrl()+"/matches/"+params.id+"/training-sessions/"+session.id+"/report",{headers:{Authorization:"Bearer "+s.access_token}});const rj=await r.json();if(!r.ok){setError(rj.message??"Unable to load report.");}else setReport(rj.data);setLoading(false)}
 useEffect(()=>{load()},[params.id]);
 async function generate(){if(!report)return;const s=await auth();if(!s)return;setGenerating(true);const r=await fetch(baseUrl()+"/matches/"+params.id+"/training-sessions/"+report.session.id+"/report/generate",{method:"POST",headers:{Authorization:"Bearer "+s.access_token}});const j=await r.json();if(!r.ok)setError(j.message??"Unable to generate report.");else setReport(j.data);setGenerating(false)}
 if(loading)return <main className="fos-loading">Loading Session Performance Report...</main>;
 const s=report?.summary;const a=report?.assessment;
 return <main className="fos-shell"><aside className="fos-sidebar"><div className="fos-brand"><strong>◆ 360<span>FOS</span></strong><small>Tactical Intelligence</small></div><nav><Link href="/">⌂ <span>Dashboard</span></Link><Link className="active" href="/matches">▣ <span>Matches</span></Link><Link href="/">⚽ <span>Training</span></Link><Link href="/">▤ <span>Reports</span></Link></nav><div className="sidebar-footer">360FOS<br/><small>Turn Analysis into Performance</small></div></aside>
 <section className="fos-main"><header className="fos-topbar"><div className="fos-search fake-search">⌕ Session Performance & Learning</div><div className="fos-user">LEARNING ENGINE <span>•</span> POST-SESSION</div></header>
 <div className="breadcrumb-row"><Link href={"/matches/"+params.id+"/training"}>Training Planner</Link><span>›</span><Link href={"/matches/"+params.id+"/training/session"}>Session Builder</Link><span>›</span><b>Performance Report</b></div>
 <section className="page-heading"><div><div className="crumb">TRAINING / PERFORMANCE & LEARNING</div><h1>{report?.session.title}</h1><p>Measure the target behaviour, validate tactical transfer, and define the next coaching action.</p></div><div className="heading-actions"><Link className="secondary-action" href={"/matches/"+params.id+"/training/session/command-center"}>← Command Center</Link><button className="primary-action" onClick={generate} disabled={generating}>{generating?"Analysing...":"Generate Learning Report ✦"}</button></div></section>
 {error&&<div className="error-box planner-message">{error}</div>}
 {report&&<><section className="command-grid"><article className="workspace-card"><span className="section-kicker">KPI SUCCESS RATE</span><div className="big-clock">{s?.successRate}%</div><p>{s?.totalReps} recorded repetitions · target {s?.targetRate}%</p></article><article className="workspace-card live-objective"><span className="section-kicker">TACTICAL TRANSFER</span><h2>{label(s?.transferRating)}</h2><p>{transferText(s?.transferRating)}</p></article><article className="workspace-card kpi-panel"><span className="section-kicker">MATCH READINESS</span><h2>{label(a?.matchReadiness)}</h2><p>{a?.nextAction??"Generate the learning report to create the next action."}</p></article></section>
 <section className="command-layout"><div><div className="section-header"><div><span className="section-kicker">EXERCISE PERFORMANCE</span><h2>Behaviour Validation</h2></div></div><div className="exercise-stack">{(report.behaviours.length?report.behaviours:report.session.exercises.map((e:any)=>({id:e.id,exerciseId:e.id,behaviour:e.matchBehaviour??e.objective,targetKpi:e.successKpi,successfulReps:0,failedReps:0,successRate:0,observation:"No exercise-level behaviour result recorded yet."}))).map((b:any,i:number)=><article className="workspace-card session-exercise" key={b.id??i}><div className="exercise-index">{String(i+1).padStart(2,"0")}</div><div className="exercise-main"><span className="section-kicker">TARGET BEHAVIOUR</span><h2>{b.behaviour}</h2><p>{b.observation}</p><div className="training-grid"><Field label="Target KPI" value={b.targetKpi}/><Field label="Success Rate" value={(b.successRate??0)+"%"}/><Field label="Successful Reps" value={String(b.successfulReps??0)}/><Field label="Failed Reps" value={String(b.failedReps??0)}/><Field label="Coach Rating" value={b.coachRating!=null?String(b.coachRating):"Not rated"}/></div></div></article>)}</div></div>
 <aside className="workspace-card coach-notes"><span className="section-kicker">COACH ASSESSMENT</span><h2>{a?.overallScore!=null?Math.round(a.overallScore):s?.successRate}%</h2><p>{a?.coachAssessment??"No additional coach assessment recorded."}</p><div className="match-transfer"><span className="section-kicker">NEXT ACTION</span><p>{a?.nextAction??"Generate the learning report."}</p></div><div className="match-transfer"><span className="section-kicker">LEARNING RESULT</span><p>{report.actions?.[0]?.result??"Pending"}</p></div></aside></section>
 <div className="ai-badge">RULE-BASED LEARNING ENGINE · COACH VALIDATION REQUIRED</div></>}
 </section></main>
}
function Field({label,value}:{label:string,value?:string|null}){return <div className="training-field"><span>{label}</span><p>{value||"Not defined"}</p></div>}
function label(v?:string){return (v??"PENDING").replaceAll("_"," ")}
function transferText(v?:string){return v==="VALIDATED"?"Target behaviour reached the configured training threshold.":v==="PARTIALLY_VALIDATED"?"Behaviour is developing but needs reinforcement before full transfer.":"Behaviour has not reached the configured threshold and should be re-taught."}
