"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function MatchPlanPage(){
 const params=useParams<{id:string}>();const router=useRouter();const [matrix,setMatrix]=useState<any|null>(null);const [priorities,setPriorities]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return;}const base=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";const h={Authorization:"Bearer "+session.access_token};const [a,b]=await Promise.all([fetch(base+"/matches/"+params.id+"/intelligence/matrix",{headers:h}),fetch(base+"/matches/"+params.id+"/training-priorities",{headers:h})]);const aj=await a.json().catch(()=>null);const bj=await b.json().catch(()=>null);const ar=aj&&typeof aj==="object"&&"data" in aj?aj.data:aj;const br=bj&&typeof bj==="object"&&"data" in bj?bj.data:bj;setMatrix(ar&&typeof ar==="object"?ar:null);setPriorities(Array.isArray(br)?br:[]);setLoading(false)})()},[params.id,router]);
 const gaps=Array.isArray(matrix?.gaps)?matrix.gaps:[]; 
 return <main className="fos-shell"><aside className="fos-sidebar"><div className="fos-brand"><strong>◆ 360<span>FOS</span></strong><small>Tactical Intelligence</small></div><nav><Link href="/">⌂ <span>Dashboard</span></Link><Link className="active" href="/matches">▣ <span>Matches</span></Link><Link href="/opponents">◌ <span>Opponents</span></Link><Link href="/training">⚽ <span>Training</span></Link><Link href="/reports">▤ <span>Reports</span></Link></nav></aside><section className="fos-main"><div className="breadcrumb-row"><Link href="/matches">Matches</Link><span>›</span><Link href={"/matches/"+params.id}>Workspace</Link><span>›</span><b>Match Plan</b></div><section className="page-heading"><div><div className="crumb">MATCH PLAN / DECISION READY</div><h1>Match Plan</h1><p>Convert approved tactical gaps and training priorities into clear match behaviours and coaching actions.</p></div><div className="heading-actions"><Link className="secondary-action" href={"/matches/"+params.id+"/intelligence"}>Intelligence Matrix</Link><Link className="secondary-action" href={"/matches/"+params.id+"/learning-loop"}>Learning Loop</Link><Link className="primary-action" href={"/matches/"+params.id+"/training"}>Training Planner →</Link></div></section>{loading?<div className="empty-state">Loading match plan...</div>:<section className="training-cards"><article className="workspace-card training-card"><span className="section-kicker">TACTICAL DECISION QUEUE</span><h2>{gaps.length} tactical gaps</h2>{gaps.length===0?<p>No tactical gaps yet. Generate intelligence from evidence, then review the Matrix.</p>:gaps.map((g:any)=><div className="match-card-bottom" key={g.id}><strong>{g.interaction}</strong><span>{g.type} · {g.priority} · {g.status}</span></div>)}</article><article className="workspace-card training-card"><span className="section-kicker">TRAINING TRANSFER</span><h2>{priorities.length} training priorities</h2>{priorities.length===0?<p>No training priorities yet. Approve a tactical gap and generate the training plan.</p>:priorities.map((p:any)=><div className="match-card-bottom" key={p.id}><strong>{p.objective}</strong><span>{p.matchObjective??"Match behaviour pending"}</span></div>)}</article></section>}</section></main>;
}
